name: fastapi
type: service
from: python
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.0"
title: Python (FastAPI)
labels:
- fastapi
- python

env:
- name: GUNICORN_APP
  value: main:app
- name: GUNICORN_WORKER_CLASS
  value: uvicorn_worker.UvicornWorker

build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: fastapi
    title: FastAPI boilerplate
    repo: https://github.com/wodby/fastapi-boilerplate
    branch: main
